[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:gateway]
command=node /app/gateway/index.js
directory=/app/gateway
environment=PORT="%(ENV_PORT)s"
autostart=true
autorestart=true
stderr_logfile=/dev/fd/1
stdout_logfile=/dev/fd/1

[program:auth-service]
command=java -Xms64m -Xmx160m -jar /app/auth-service.jar
directory=/app
environment=PORT="8081",SPRING_DATASOURCE_URL="%(ENV_DB_URL)s",SPRING_DATASOURCE_USERNAME="%(ENV_DB_USER)s",SPRING_DATASOURCE_PASSWORD="%(ENV_DB_PASS)s",JWT_SECRET="%(ENV_JWT_SECRET)s",CORS_ALLOWED_ORIGINS="%(ENV_CORS)s"
autostart=true
autorestart=true
stderr_logfile=/dev/fd/1
stdout_logfile=/dev/fd/1

[program:product-service]
command=java -Xms64m -Xmx160m -jar /app/product-service.jar
directory=/app
environment=PORT="8082",SPRING_DATASOURCE_URL="%(ENV_DB_URL)s",SPRING_DATASOURCE_USERNAME="%(ENV_DB_USER)s",SPRING_DATASOURCE_PASSWORD="%(ENV_DB_PASS)s",JWT_SECRET="%(ENV_JWT_SECRET)s",AUDIT_SERVICE_URL="http://localhost:8084",CORS_ALLOWED_ORIGINS="%(ENV_CORS)s"
autostart=true
autorestart=true
stderr_logfile=/dev/fd/1
stdout_logfile=/dev/fd/1

[program:payment-service]
command=node /app/payment-service/src/index.js
directory=/app/payment-service
environment=PORT="8083",JWT_SECRET="%(ENV_JWT_SECRET)s",STRIPE_SECRET_KEY="%(ENV_STRIPE_SECRET_KEY)s",STRIPE_WEBHOOK_SECRET="%(ENV_STRIPE_WEBHOOK_SECRET)s",STRIPE_SUCCESS_URL="%(ENV_FRONTEND_URL)s/success",STRIPE_CANCEL_URL="%(ENV_FRONTEND_URL)s/cart",PRODUCT_SERVICE_HOST="localhost",PRODUCT_SERVICE_PORT="8082",NOTIFICATION_SERVICE_HOST="localhost",NOTIFICATION_SERVICE_PORT="8086",CORS_ALLOWED_ORIGINS="%(ENV_CORS)s"
autostart=true
autorestart=true
stderr_logfile=/dev/fd/1
stdout_logfile=/dev/fd/1

[program:audit-service]
command=uvicorn main:app --host 0.0.0.0 --port 8084
directory=/app/audit-service
environment=PORT="8084",MONGO_URI="%(ENV_MONGO_URI)s",AI_ENGINE_HOST="localhost",AI_ENGINE_PORT="8085",PRODUCT_SERVICE_HOST="localhost",PRODUCT_SERVICE_PORT="8082",CORS_ALLOWED_ORIGINS="%(ENV_CORS)s"
autostart=true
autorestart=true
stderr_logfile=/dev/fd/1
stdout_logfile=/dev/fd/1

[program:ai-engine]
command=uvicorn main:app --host 0.0.0.0 --port 8085
directory=/app/ai-engine
environment=PORT="8085"
autostart=true
autorestart=true
stderr_logfile=/dev/fd/1
stdout_logfile=/dev/fd/1

[program:notification-service]
command=uvicorn main:app --host 0.0.0.0 --port 8086
directory=/app/notification-service
environment=PORT="8086"
autostart=true
autorestart=true
stderr_logfile=/dev/fd/1
stdout_logfile=/dev/fd/1
